CREATE TABLE Customer (
CustomerID SERIAL PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
Phone VARCHAR(20) UNIQUE NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL
);
CREATE TABLE Category (
CategoryID SERIAL PRIMARY KEY NOT NULL,
Name VARCHAR(50) NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL
);
CREATE TABLE Product (
ProductID SERIAL PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL,
Description TEXT,
Price DECIMAL(10,2) NOT NULL,
Stock INT NOT NULL,
CategoryID INT NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
CONSTRAINT fk_Product_Category FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
);
CREATE TABLE Employee (
EmployeeID SERIAL PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Position VARCHAR(50) NOT NULL,
AccessPrivileges VARCHAR(100) NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL
);






CREATE TABLE PriceHistory (
ProductID SERIAL NOT NULL,
Price DECIMAL(10,2) NOT NULL,
EffectiveDate DATE NOT NULL,
ChangeReason TEXT,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
PRIMARY KEY (ProductID, EffectiveDate),
CONSTRAINT fk_PriceHistory_Product FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);
CREATE TABLE DeliveryAddress (
AddressID SERIAL PRIMARY KEY NOT NULL,
CustomerID INT NOT NULL,
Street VARCHAR(100) NOT NULL,
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
PostalCode VARCHAR(20) NOT NULL,
Country VARCHAR(50) NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
CONSTRAINT fk_DeliveryAddress_Customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);
CREATE TABLE Orders (
OrderID SERIAL PRIMARY KEY NOT NULL,
OrderDate DATE NOT NULL,
CustomerID INT NOT NULL,
EmployeeID INT NOT NULL,
TotalAmount DECIMAL(10,2) NOT NULL,
DeliveryAddressID INT NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
CONSTRAINT fk_Orders_Customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
CONSTRAINT fk_Orders_Employee FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID),
CONSTRAINT fk_Orders_DeliveryAddress FOREIGN KEY (DeliveryAddressID) REFERENCES DeliveryAddress(AddressID)
);
CREATE TABLE OrderDetails (
OrderDetailID SERIAL PRIMARY KEY NOT NULL,
OrderID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
CONSTRAINT fk_OrderDetails_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
CONSTRAINT fk_OrderDetails_Product FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);


CREATE TABLE Payment (
PaymentID SERIAL PRIMARY KEY NOT NULL,
OrderID INT NOT NULL,
CustomerID INT NOT NULL,
Amount DECIMAL(10,2) NOT NULL,
PaymentDate DATE NOT NULL,
PaymentMethod VARCHAR(50) NOT NULL,
CreatedBy VARCHAR(50) NOT NULL,
UpdatedBy VARCHAR(50) NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
UpdatedAt TIMESTAMP NOT NULL,
CONSTRAINT fk_Payment_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
CONSTRAINT fk_Payment_Customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);
